Refactor install script
nagygergo/jetbrains-toolbox-install pull request #17
Opened 2023-05-04 17:16 UTC by JanPokorny

I propose some changes for the install script.

- **No sudo needed** -- JetBrains toolbox is installed to `~/.local/share/JetBrains/Toolbox` where it wants to reside anyway
- Removed some useless elements (some curl params, needless function, etc.)
- The binary is now not extracted to `/opt` (fixes #14), but to the actual location where JetBrains Toolbox installs itself after first run
- The symlink is set to point correctly to the installed toolbox binary (fixes #16) and is in a user-specific folder as well
- Make the script output nicer, more structured

2023-05-27 14:42 UTC, nagygergo requested changes
Please update the github action to look for the symlink at the new place.

2023-05-27 14:42 UTC, nagygergo commented on jetbrains-toolbox.sh
> +rm "$SYMLINK_DIR/jetbrains-toolbox"
Please handle the error when the symlink dir doesn't exists

2023-05-27 16:46 UTC, JanPokorny commented
@nagygergo Should be fixed! I had to hardcode the path to binary in the workflow since docker images usually don't put `~/.local/bin` to PATH, but most desktop distros do.

2023-05-28 12:36 UTC, JanPokorny commented
Looks like the run failed because the CI container can't run AppImages

2023-05-29 08:41 UTC, JanPokorny commented
This should hopefully fix stuff

2023-06-24 12:04 UTC, merged

2023-06-24 12:04 UTC, nagygergo commented
Great, I have no more comments, merging it. 
Thanks for the contribution.

2023-06-24 12:05 UTC, nagygergo reviewed
Looks good